apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  schemaVersion: v1.0.0
  name: openapi-generator
  description: OpenAPI Generator allows generation of API client libraries (SDK generation), server stubs, documentation and configuration automatically given an OpenAPI Spec (v2, v3)
  annotations:
    github.com/project-slug: Bandwidth/openapi-generator
    organization: BW
    costCenter: Development - Software Infra
spec:
  type: Service
  owner: github/band-swi
  lifecycle: Available
